spring:
  profiles:
    include: file

  resources:
    static-locations: classpath:/static/

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/notice-service
      username: sa
      password: 12
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  cache:
    type: redis

  redis:
    port: 6379
    host: localhost

  session:
    store-type: redis
    redis:
      flush-mode: on_save

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      file-size-threshold: 1
      max-file-size: 10
      max-request-size: 30
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  config: classpath:log4j2.xml
  charset:
    console: utf-8